import { generateKeyPairSync } from "node:crypto";
import { readFile } from "node:fs/promises";
import { describe, expect, it } from "vitest";
import { isVaultFingerprint, sealVaultRing, vaultFingerprint } from "../src/vault-crypto.js";
import { openTestVaultBox, type VaultFixture } from "./support/vault.js";

// Byte-for-byte copy of the reviewed Go fixture, never regenerated by tests.
const fx = JSON.parse(await readFile(new URL("./fixtures/vault.json", import.meta.url), "utf8")) as VaultFixture;

describe("vault ring crypto", () => {
  it("opens Go's box and derives the exact grouped fingerprint", () => {
    expect(openTestVaultBox(fx, fx.prefix, fx.box)).toBe(fx.ring);
    expect(vaultFingerprint(fx.pub)).toBe("NGF6 UY64 ISRU IZR7 6FBJ V2QQ QQ");
  });

  it("seals the layout opened independently and binds prefix and fingerprint", () => {
    const box = sealVaultRing(fx.pub, fx.prefix, fx.ring);
    const raw = Buffer.from(box, "base64url");
    expect(raw).toHaveLength(125);
    expect(raw[0]).toBe(4);
    expect(raw.toString("base64url")).toBe(box);
    expect(openTestVaultBox(fx, fx.prefix, box)).toBe(fx.ring);
    expect(() => openTestVaultBox(fx, "fmrl_else", box)).toThrow();
    expect(() => openTestVaultBox({ ...fx, fingerprint: fx.fingerprint.replace("N", "A") }, fx.prefix, box)).toThrow();
    expect(sealVaultRing(fx.pub, fx.prefix, fx.ring)).not.toBe(box);
  });

  it("authenticates nonce, ciphertext and tag", () => {
    const box = sealVaultRing(fx.pub, fx.prefix, fx.ring);
    for (const offset of [65, 77, 109]) {
      const raw = Buffer.from(box, "base64url");
      raw[offset] ^= 1;
      expect(() => openTestVaultBox(fx, fx.prefix, raw.toString("base64url"))).toThrow();
    }
  });

  it("refuses opening under a foreign private key", () => {
    const foreign = generateKeyPairSync("ec", { namedCurve: "prime256v1" }).privateKey
      .export({ format: "der", type: "pkcs8" }).toString("base64url");
    const box = sealVaultRing(fx.pub, fx.prefix, fx.ring);
    expect(() => openTestVaultBox({ ...fx, private_pkcs8: foreign }, fx.prefix, box)).toThrow();
  });

  it("rejects malformed public keys without reflecting input", () => {
    const invalidPoint = Buffer.alloc(65);
    invalidPoint[0] = 4; // Correct wire length and marker, invalid curve coordinates.
    const badKeys = ["", fx.pub + "=", fx.pub + "\n", "A".repeat(87), invalidPoint.toString("base64url")];
    for (const bad of badKeys) {
      expect(() => vaultFingerprint(bad)).toThrow(new Error("invalid vault public key"));
      expect(() => sealVaultRing(bad, fx.prefix, fx.ring)).toThrow(new Error("invalid vault public key"));
    }
  });

  it("rejects noncanonical public key trailing bits even when Buffer decodes the same point", () => {
    const noncanonical = fx.pub.slice(0, -1) + "V";
    expect(noncanonical).not.toBe(fx.pub);
    expect(Buffer.from(noncanonical, "base64url")).toEqual(Buffer.from(fx.pub, "base64url"));
    expect(() => vaultFingerprint(noncanonical)).toThrow(new Error("invalid vault public key"));
    expect(() => sealVaultRing(noncanonical, fx.prefix, fx.ring)).toThrow(new Error("invalid vault public key"));
  });

  it("recognizes only grouped RFC4648 fingerprints with canonical final padding bits", () => {
    expect(isVaultFingerprint(fx.fingerprint)).toBe(true);
    for (const final of "AEIMQUY4") {
      expect(isVaultFingerprint(fx.fingerprint.slice(0, -1) + final)).toBe(true);
    }
    for (const bad of [undefined, null, 26, "K7QM 2XDA 9TRV HB3E", fx.fingerprint.replaceAll(" ", ""),
      fx.fingerprint.toLowerCase(), fx.fingerprint + "\n", fx.fingerprint.slice(0, -1) + "R",
      fx.fingerprint.replace("N", "9"), fx.fingerprint.replace(" ", "\t")]) {
      expect(isVaultFingerprint(bad)).toBe(false);
    }
  });

  it("requires a four-character alphanumeric key prefix", () => {
    for (const bad of ["", "fmrl_test.2", "fmrl_abc", "fmrl_abcde", "fmrl_ab-c", "fmrl_test\n"]) {
      expect(() => sealVaultRing(fx.pub, bad, fx.ring)).toThrow(new Error("invalid vault ring prefix"));
    }
    expect(openTestVaultBox(fx, "fmrl_A1z9", sealVaultRing(fx.pub, "fmrl_A1z9", fx.ring))).toBe(fx.ring);
  });

  it("requires exactly 32 ring bytes in canonical unpadded base64url", () => {
    const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";
    const noncanonical = fx.ring.slice(0, -1) + alphabet[alphabet.indexOf(fx.ring.at(-1)!) + 1];
    expect(noncanonical).not.toBe(fx.ring);
    expect(Buffer.from(noncanonical, "base64url")).toEqual(Buffer.from(fx.ring, "base64url"));
    for (const bad of ["", "A".repeat(42), "A".repeat(44), "A".repeat(43) + "=", fx.ring + "\n",
      "!" + fx.ring.slice(1), noncanonical]) {
      expect(() => sealVaultRing(fx.pub, fx.prefix, bad)).toThrow(new Error("invalid vault ring"));
    }
  });
});
